name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python Enviornment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Update Requirements.txt
      run: |
        pip freeze > requirements.txt
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git add requirements.txt
        git commit -m "Update requirements.txt"
        git push origin main
        
    - name: Run Tests
      run: python tests.py
